# Workflow based on a template by @cpintado

# name of the workflow: will be visible in the dashboard and in Splunk
name: template by @cpintado

# Trigger the workflow when the Star button is clicked
on:
  watch:
    types:
      - started

# list of jobs, creat more than one if necessary
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
